name: Update publications

on:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5

    - name: "Install dependencies"
      run: pip install ads jinja2

    - name: "Update publication list"
      run: python utils/get_publications.py

    - name: Commit & Push changes
      uses: actions-js/push@v1.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}